[project]
name = "lproto"
description = ""
authors = [{ name = "Hyeonki Hong", email = "hhk7734@gmail.com" }]
requires-python = ">=3.8,<4.0"

dynamic = ["version"]

dependencies = ["protobuf", "grpcio"]

[tool.setuptools_scm]
root = "../.."
tag_regex = '^(?P<version>[vV]?\d+(?:\.\d+){0,2}[^\+]*)(?:\+.*)?$'
git_describe_command = 'git describe --dirty --tags --long --match "v[0-9]*"'

[tool.setuptools]
zip-safe = false

[tool.setuptools.package-data]
"*" = ["py.typed", "*.pyi"]

[tool.setuptools.packages.find]
include = ["lproto", "lproto.*"]

[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"
